TEMPLATE_TAREFAS = [
    # ── PASSAGEM TERRENOS-NEGÓCIOS ──────────────────────────────────────────
    {
        "id": "passagem_terrenos",
        "nome": "Passagem Terrenos-Negócios",
        "grupo": "Passagem Terrenos-Negócios",
        "subgrupo": None,
        "fase": "Passagem Terrenos-Negócios",
        "duracao_dias": 1,
        "dependencias": [],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Evento de passagem formal do terreno da área de Negócios para Incorporação.",
    },
    {
        "id": "reuniao_passagem_terreno",
        "nome": "Reunião de Passagem do Terreno",
        "grupo": "Passagem Terrenos-Negócios",
        "subgrupo": None,
        "fase": "Passagem Terrenos-Negócios",
        "duracao_dias": 1,
        "dependencias": ["passagem_terrenos"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Reunião interna de alinhamento sobre o terreno entre as equipes.",
    },
    {
        "id": "pre_comar",
        "nome": "Pré-COMAR",
        "grupo": "Passagem Terrenos-Negócios",
        "subgrupo": None,
        "fase": "Passagem Terrenos-Negócios",
        "duracao_dias": 20,
        "dependencias": ["reuniao_passagem_terreno"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Consulta técnica preliminar com a prefeitura sobre viabilidade e enquadramento.",
    },
    {
        "id": "ficha_tecnica",
        "nome": "Ficha Técnica",
        "grupo": "Passagem Terrenos-Negócios",
        "subgrupo": None,
        "fase": "Passagem Terrenos-Negócios",
        "duracao_dias": 20,
        "dependencias": ["reuniao_passagem_terreno"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Documento interno com parâmetros iniciais do terreno e projeto.",
    },
    # ── LEVANTAMENTOS INICIAIS — sem subgrupo ───────────────────────────────
    {
        "id": "acesso_terreno",
        "nome": "Acesso Terreno",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 1,
        "dependencias": ["passagem_terrenos"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Solicitação e liberação de acesso físico ao terreno para levantamentos.",
    },
    {
        "id": "vistoria_terreno",
        "nome": "Vistoria do Terreno",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 15,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Visita técnica ao terreno para verificação das condições físicas e confrontantes.",
    },
    {
        "id": "planialtimetrico",
        "nome": "Levantamento Planialtimétrico",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 30,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Levanta altitudes e contornos do terreno para projeto.",
    },
    {
        "id": "laudo_hidrologico",
        "nome": "Estudo Hidrológico",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 60,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Projetos",
        "descricao": "Avalia impacto de drenagem e risco de enchente.",
    },
    {
        "id": "sondagem",
        "nome": "Pré Sondagem",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 45,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Orçamentos",
        "descricao": "Avaliação do solo para fundações.",
    },
    {
        "id": "orcamento_demolicao",
        "nome": "Orçamento da Demolição",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 15,
        "dependencias": ["vistoria_terreno"],
        "condicional": None,
        "responsavel": "Engenharia",
        "descricao": "Levantamento do custo para execução da demolição das estruturas existentes.",
    },
    {
        "id": "reuniao_passagem_ep",
        "nome": "Reunião de Passagem EP",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 1,
        "dependencias": ["vistoria_terreno"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Reunião de passagem do Estudo Preliminar entre as equipes.",
    },
    {
        "id": "diretrizes_agua_esgoto",
        "nome": "Diretrizes de Água e Esgoto",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 60,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Levantamento das diretrizes de abastecimento de água e coleta de esgoto.",
    },
    {
        "id": "diretrizes_energia",
        "nome": "Diretrizes de Energia",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": None,
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 60,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Levantamento das diretrizes de fornecimento de energia elétrica.",
    },
    # ── LEVANTAMENTOS INICIAIS — Estudos Ambientais ─────────────────────────
    {
        "id": "investigacao_ambiental",
        "nome": "Estudos de Passivo",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Estudos Ambientais",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 120,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Meio Ambiente",
        "descricao": "Estudos técnicos detalhados sobre passivo ambiental identificado no terreno.",
    },
    {
        "id": "estimativa_custo_passivo",
        "nome": "Estimativa de Custo Passivo Ambiental",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Estudos Ambientais",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 75,
        "dependencias": ["investigacao_ambiental"],
        "condicional": None,
        "responsavel": "Meio Ambiente",
        "descricao": "Estimativa financeira do custo de remediação do passivo ambiental.",
    },
    {
        "id": "cadastro_arboreo",
        "nome": "Cadastramento Arbóreo",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Estudos Ambientais",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 30,
        "dependencias": ["acesso_terreno"],
        "condicional": None,
        "responsavel": "Meio Ambiente",
        "descricao": "Conta e classifica árvores para entender se haverá remoção.",
    },
    {
        "id": "relatorio_final_passivo",
        "nome": "Relatório Final Passivo Ambiental",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Estudos Ambientais",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 60,
        "dependencias": ["estimativa_custo_passivo"],
        "condicional": None,
        "responsavel": "Meio Ambiente",
        "descricao": "Relatório final consolidando todos os estudos de passivo ambiental.",
    },
    {
        "id": "tca",
        "nome": "Termo de Compromisso Ambiental - TCA",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Estudos Ambientais",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 90,
        "dependencias": ["relatorio_final_passivo"],
        "condicional": None,
        "responsavel": "Meio Ambiente",
        "descricao": "Termo de compromisso firmado com órgão ambiental para remediação.",
    },
    {
        "id": "custos_ambientais_ccl",
        "nome": "Custos Ambientais CCL",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Estudos Ambientais",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 30,
        "dependencias": ["estimativa_custo_passivo"],
        "condicional": None,
        "responsavel": "Meio Ambiente",
        "descricao": "Levantamento de custos ambientais para CCL.",
    },
    # ── LEVANTAMENTOS INICIAIS — Jurídico ───────────────────────────────────
    {
        "id": "due_diligence",
        "nome": "Due Diligence",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Jurídico",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 90,
        "dependencias": ["reuniao_passagem_terreno"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Investigação completa: jurídica, ambiental, técnica e fiscal do terreno.",
    },
    {
        "id": "analise_juridica_matricula",
        "nome": "Análise Jurídica e Técnica da Matrícula",
        "grupo": "Levantamentos Iniciais",
        "subgrupo": "Jurídico",
        "fase": "Levantamentos Iniciais",
        "duracao_dias": 75,
        "dependencias": ["due_diligence"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Verificar se a matrícula está limpa, sem pendências judiciais ou restrições.",
    },
    # ── DESENVOLVIMENTO DE PROJETO ──────────────────────────────────────────
    {
        "id": "confirmacao_mix",
        "nome": "Confirmação Mix",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 30,
        "dependencias": ["ficha_tecnica"],
        "condicional": None,
        "responsavel": "Produto",
        "descricao": "Confirmação do mix de unidades do empreendimento.",
    },
    {
        "id": "classificacao_ruido",
        "nome": "Classificação do Ruído",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 30,
        "dependencias": ["vistoria_terreno"],
        "condicional": None,
        "responsavel": "Projetos",
        "descricao": "Classificação acústica do entorno do terreno.",
    },
    {
        "id": "ca_confirmacao_interna",
        "nome": "CA de Confirmação Interna",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 15,
        "dependencias": ["confirmacao_mix"],
        "condicional": None,
        "responsavel": "Produto",
        "descricao": "Confirmação interna do coeficiente de aproveitamento.",
    },
    {
        "id": "eva",
        "nome": "EVA (Estudo de Viabilidade Arquitetônica)",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 60,
        "dependencias": ["planialtimetrico"],
        "condicional": None,
        "responsavel": "Produto",
        "descricao": "Testa quantos m² e unidades cabem, respeitando o zoneamento.",
    },
    {
        "id": "diretriz_sabesp",
        "nome": "Diretriz SABESP",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 60,
        "dependencias": ["eva"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Consulta à Sabesp para verificar viabilidade de abastecimento de água e esgoto.",
    },
    {
        "id": "ep",
        "nome": "EP (Estudo Preliminar)",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 105,
        "dependencias": ["eva"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Primeira versão do projeto arquitetônico com base na viabilidade e zoneamento.",
    },
    {
        "id": "validacao_ep",
        "nome": "Validação EP",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 15,
        "dependencias": ["ep"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Validação interna do Estudo Preliminar.",
    },
    {
        "id": "ep_arq_compatibilizado",
        "nome": "EP Arquitetura Compatibilizado",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 30,
        "dependencias": ["validacao_ep"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "EP com todas as disciplinas compatibilizadas.",
    },
    {
        "id": "ap",
        "nome": "AP (Anteprojeto)",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 180,
        "dependencias": ["ep_arq_compatibilizado"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Versão intermediária do projeto arquitetônico para fins de aprovação.",
    },
    {
        "id": "revisao_final_ep",
        "nome": "Revisão Final do EP/Base R00 AP",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 20,
        "dependencias": ["ep_arq_compatibilizado"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Revisão final do EP como base para o R00 do AP.",
    },
    {
        "id": "ap_arq_compatibilizado",
        "nome": "AP Arquitetura Compatibilizado",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 30,
        "dependencias": ["ap"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "AP com todas as disciplinas compatibilizadas.",
    },
    {
        "id": "ap_final_orcamento",
        "nome": "AP Final para Orçamento",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 20,
        "dependencias": ["ap_arq_compatibilizado"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Versão final do AP liberada para orçamento.",
    },
    {
        "id": "executivo",
        "nome": "Executivo",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 240,
        "dependencias": ["ap_arq_compatibilizado"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Projeto técnico completo e detalhado com todas as disciplinas.",
    },
    {
        "id": "pl_sabesp",
        "nome": "PL Sabesp",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 30,
        "dependencias": ["ap"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Projeto Legal específico para protocolo na Sabesp.",
    },
    {
        "id": "pl_protocolo",
        "nome": "PL Protocolo",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 30,
        "dependencias": ["ap"],
        "condicional": None,
        "responsavel": "Legalização",
        "descricao": "Projeto Legal para protocolo na prefeitura.",
    },
    {
        "id": "pl_final",
        "nome": "PL Final",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 30,
        "dependencias": ["pl_protocolo"],
        "condicional": None,
        "responsavel": "Legalização",
        "descricao": "Projeto Legal definitivo com todos os ajustes solicitados.",
    },
    {
        "id": "pl_cartorio",
        "nome": "PL Cartório",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 20,
        "dependencias": ["pl_final"],
        "condicional": None,
        "responsavel": "Legalização",
        "descricao": "Projeto Legal para registro em cartório.",
    },
    {
        "id": "elaboracao_projetos_sabesp",
        "nome": "Elaboração Projetos de Reforço Sabesp",
        "grupo": "Desenvolvimento de Projeto",
        "subgrupo": None,
        "fase": "Desenvolvimento de Projeto",
        "duracao_dias": 60,
        "dependencias": ["pl_sabesp"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Elaboração dos projetos de reforço da infraestrutura Sabesp.",
    },
    # ── APROVAÇÕES LEGAIS — Aprovações Municipais ───────────────────────────
    {
        "id": "ceuso",
        "nome": "CEUSO",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 120,
        "dependencias": ["ep"],
        "condicional": "ceuso",
        "responsavel": "Legalização",
        "descricao": "Comissão que avalia pedidos de exceção às regras do zoneamento.",
    },
    {
        "id": "depave",
        "nome": "DEPAVE",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 90,
        "dependencias": ["cadastro_arboreo"],
        "condicional": "depave",
        "responsavel": "Meio Ambiente",
        "descricao": "Autorização de remoção de vegetação e interferência arbórea.",
    },
    {
        "id": "comar_completo",
        "nome": "COMAR Completo",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 120,
        "dependencias": ["pre_comar"],
        "condicional": "comar",
        "responsavel": "Legalização",
        "descricao": "Aprovação formal do projeto junto à Comissão de Análise da prefeitura.",
    },
    {
        "id": "projeto_sabesp",
        "nome": "Projeto SABESP",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 60,
        "dependencias": ["elaboracao_projetos_sabesp"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Projeto técnico da infraestrutura de água e esgoto baseado na diretriz aprovada.",
    },
    {
        "id": "alvara_aprovacao",
        "nome": "Alvará de Aprovação",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 180,
        "dependencias": ["ap", "cetesb"],
        "condicional": None,
        "responsavel": "Legalização",
        "descricao": "Documento que autoriza oficialmente a execução da obra conforme projeto aprovado.",
    },
    {
        "id": "aprovacao_completa",
        "nome": "Aprovação Completa",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 90,
        "dependencias": ["alvara_aprovacao"],
        "condicional": None,
        "responsavel": "Legalização",
        "descricao": "Aprovação completa do projeto junto aos órgãos municipais.",
    },
    {
        "id": "alvara_execucao",
        "nome": "Alvará de Execução",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 60,
        "dependencias": ["alvara_aprovacao"],
        "condicional": None,
        "responsavel": "Legalização",
        "descricao": "Alvará que autoriza o início da execução da obra.",
    },
    {
        "id": "alvara_tapume",
        "nome": "Alvará de Tapume",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 30,
        "dependencias": ["alvara_aprovacao"],
        "condicional": None,
        "responsavel": "Engenharia",
        "descricao": "Autorização para instalação de tapume no terreno.",
    },
    {
        "id": "montagem_processo_regularizacao",
        "nome": "Montagem do Processo de Regularização",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Municipais",
        "fase": "Aprovações Legais",
        "duracao_dias": 45,
        "dependencias": ["alvara_aprovacao"],
        "condicional": None,
        "responsavel": "Legalização",
        "descricao": "Montagem de toda a documentação para o processo de regularização.",
    },
    # ── APROVAÇÕES LEGAIS — Aprovações Estaduais ────────────────────────────
    {
        "id": "cetesb",
        "nome": "CETESB",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Estaduais",
        "fase": "Aprovações Legais",
        "duracao_dias": 180,
        "dependencias": ["investigacao_ambiental"],
        "condicional": None,
        "responsavel": "Meio Ambiente",
        "descricao": "Licenciamento ambiental obrigatório para terrenos com passivo ambiental.",
    },
    {
        "id": "decont",
        "nome": "DECONT",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Estaduais",
        "fase": "Aprovações Legais",
        "duracao_dias": 90,
        "dependencias": ["cetesb"],
        "condicional": "decont",
        "responsavel": "Meio Ambiente",
        "descricao": "Aprovação do processo de descontaminação de terrenos contaminados.",
    },
    {
        "id": "condephaat",
        "nome": "CONDEPHAAT",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Estaduais",
        "fase": "Aprovações Legais",
        "duracao_dias": 120,
        "dependencias": ["ficha_tecnica"],
        "condicional": "condephaat",
        "responsavel": "Legalização",
        "descricao": "Avaliação junto ao Conselho de Defesa do Patrimônio Histórico do Estado.",
    },
    {
        "id": "graprohab",
        "nome": "GRAPROHAB",
        "grupo": "Aprovações Legais",
        "subgrupo": "Aprovações Estaduais",
        "fase": "Aprovações Legais",
        "duracao_dias": 180,
        "dependencias": ["projeto_sabesp"],
        "condicional": "graprohab",
        "responsavel": "Legalização",
        "descricao": "Aprovação de projetos habitacionais de interesse social (800+ unidades).",
    },
    # ── APROVAÇÕES LEGAIS — Registro e Cartório ─────────────────────────────
    {
        "id": "retificacao",
        "nome": "Retificação",
        "grupo": "Aprovações Legais",
        "subgrupo": "Registro e Cartório",
        "fase": "Aprovações Legais",
        "duracao_dias": 105,
        "dependencias": ["analise_juridica_matricula"],
        "condicional": "retificacao",
        "responsavel": "Jurídico",
        "descricao": "Processo cartorial para corrigir divergências nas medidas ou área da matrícula.",
    },
    {
        "id": "desmembramento",
        "nome": "Desmembramento",
        "grupo": "Aprovações Legais",
        "subgrupo": "Registro e Cartório",
        "fase": "Aprovações Legais",
        "duracao_dias": 180,
        "dependencias": ["analise_juridica_matricula"],
        "condicional": "desmembramento",
        "responsavel": "Legalização",
        "descricao": "Divisão legal de uma área maior em duas ou mais porções independentes.",
    },
    {
        "id": "unificacao_matricula",
        "nome": "Unificação da Matrícula",
        "grupo": "Aprovações Legais",
        "subgrupo": "Registro e Cartório",
        "fase": "Aprovações Legais",
        "duracao_dias": 90,
        "dependencias": ["analise_juridica_matricula"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Unificação de matrículas distintas em uma única matrícula.",
    },
    {
        "id": "laudo_posse",
        "nome": "Laudo de Posse",
        "grupo": "Aprovações Legais",
        "subgrupo": "Registro e Cartório",
        "fase": "Aprovações Legais",
        "duracao_dias": 30,
        "dependencias": ["analise_juridica_matricula"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Laudo técnico que comprova a posse do terreno.",
    },
    {
        "id": "imissao_posse",
        "nome": "Imissão da Posse",
        "grupo": "Aprovações Legais",
        "subgrupo": "Registro e Cartório",
        "fase": "Aprovações Legais",
        "duracao_dias": 45,
        "dependencias": ["laudo_posse"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Processo de imissão formal na posse do terreno.",
    },
    {
        "id": "laudo_vizinhos",
        "nome": "Laudo de Vizinhos",
        "grupo": "Aprovações Legais",
        "subgrupo": "Registro e Cartório",
        "fase": "Aprovações Legais",
        "duracao_dias": 30,
        "dependencias": ["vistoria_terreno"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Laudo técnico sobre as condições dos imóveis vizinhos.",
    },
    {
        "id": "regularizacao_contribuinte",
        "nome": "Regularização do Contribuinte",
        "grupo": "Aprovações Legais",
        "subgrupo": "Registro e Cartório",
        "fase": "Aprovações Legais",
        "duracao_dias": 30,
        "dependencias": ["analise_juridica_matricula"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Regularização fiscal e tributária do contribuinte junto à prefeitura.",
    },
    # ── PREPARATIVOS LANÇAMENTO — Registro e Cartório ───────────────────────
    {
        "id": "escritura",
        "nome": "Escritura",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["alvara_aprovacao"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Instrumento público que formaliza a transferência da propriedade do terreno.",
    },
    {
        "id": "abertura_matricula",
        "nome": "Abertura de Matrícula",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["desmembramento"],
        "condicional": "desmembramento",
        "responsavel": "Jurídico",
        "descricao": "Criação de nova matrícula individual no cartório.",
    },
    {
        "id": "instrumentos_incorporacao",
        "nome": "Instrumentos de Incorporação",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["alvara_aprovacao"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Documentos legais que formalizam o registro do empreendimento no cartório.",
    },
    {
        "id": "ri",
        "nome": "RI (Registro de Incorporação)",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 45,
        "dependencias": ["instrumentos_incorporacao"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Registro oficial do empreendimento no cartório de imóveis.",
    },
    {
        "id": "ri_prenotacao",
        "nome": "RI - Prenotação",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 15,
        "dependencias": ["instrumentos_incorporacao"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Prenotação do registro de incorporação no cartório.",
    },
    {
        "id": "ri_obtencao",
        "nome": "RI - Obtenção",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["ri_prenotacao"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Obtenção do registro de incorporação no cartório.",
    },
    {
        "id": "memorial_descritivo",
        "nome": "Memorial Descritivo",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 20,
        "dependencias": ["ap_final_orcamento"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Documento técnico descritivo do empreendimento.",
    },
    {
        "id": "planta_contrato",
        "nome": "Planta de Contrato",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Registro e Cartório",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 20,
        "dependencias": ["ap_final_orcamento"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Planta oficial do empreendimento para anexo contratual.",
    },
    # ── PREPARATIVOS LANÇAMENTO — Comercialização ───────────────────────────
    {
        "id": "lae",
        "nome": "LAE",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 180,
        "dependencias": ["alvara_aprovacao"],
        "condicional": None,
        "responsavel": "Captação Recursos",
        "descricao": "Licença de Aprovação de Empreendimento junto à Caixa Econômica Federal.",
    },
    {
        "id": "contratacao_cef",
        "nome": "Contratação CEF",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["ri", "lae"],
        "condicional": None,
        "responsavel": "Captação Recursos",
        "descricao": "Formalização do contrato de financiamento com a Caixa Econômica Federal.",
    },
    {
        "id": "briefing_inicial",
        "nome": "Briefing Inicial",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 15,
        "dependencias": ["confirmacao_mix"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Briefing inicial para o time de marketing e vendas.",
    },
    {
        "id": "materiais_vendas",
        "nome": "Materiais de Vendas",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 60,
        "dependencias": ["ep"],
        "condicional": None,
        "responsavel": "Produto",
        "descricao": "Peças publicitárias e promocionais para divulgação do empreendimento.",
    },
    {
        "id": "mkt_preparacao",
        "nome": "MKT Preparação",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 60,
        "dependencias": ["materiais_vendas"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Planejamento e execução das estratégias de marketing para o lançamento.",
    },
    {
        "id": "projeto_stand",
        "nome": "Projeto Stand",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["briefing_inicial"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Projeto do stand de vendas do empreendimento.",
    },
    {
        "id": "execucao_stand",
        "nome": "Execução de Stand",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 45,
        "dependencias": ["projeto_stand"],
        "condicional": None,
        "responsavel": "Engenharia/PDV",
        "descricao": "Execução física do stand de vendas.",
    },
    {
        "id": "imagens",
        "nome": "Imagens",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["briefing_inicial"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Produção de imagens do empreendimento para material de vendas.",
    },
    {
        "id": "tour_virtual",
        "nome": "Tour Virtual",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["imagens"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Produção do tour virtual do empreendimento.",
    },
    {
        "id": "maquete",
        "nome": "Maquete",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 45,
        "dependencias": ["briefing_inicial"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Produção da maquete física ou virtual do empreendimento.",
    },
    {
        "id": "materiais_offline",
        "nome": "Materiais Offline",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["briefing_inicial"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Produção de materiais físicos de vendas (folder, book, etc.).",
    },
    {
        "id": "materiais_online",
        "nome": "Materiais Online",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["briefing_inicial"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Produção de materiais digitais de vendas.",
    },
    {
        "id": "orcamento_final",
        "nome": "Orçamento Final",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["ap_final_orcamento"],
        "condicional": None,
        "responsavel": "Orçamentos",
        "descricao": "Orçamento final do empreendimento.",
    },
    {
        "id": "tabela_espelho_vendas",
        "nome": "Tabela e Espelho de Vendas",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 15,
        "dependencias": ["orcamento_final"],
        "condicional": None,
        "responsavel": "Produto",
        "descricao": "Tabela de preços e espelho de vendas das unidades.",
    },
    {
        "id": "previsao_condominio",
        "nome": "Previsão de Condomínio",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 15,
        "dependencias": ["ap_final_orcamento"],
        "condicional": None,
        "responsavel": "Produto",
        "descricao": "Previsão orçamentária do condomínio.",
    },
    {
        "id": "contrato_cliente",
        "nome": "Contrato Cliente",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 20,
        "dependencias": ["instrumentos_incorporacao"],
        "condicional": None,
        "responsavel": "Jurídico",
        "descricao": "Minuta do contrato de compra e venda com o cliente.",
    },
    {
        "id": "cadastro",
        "nome": "Cadastro",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 15,
        "dependencias": ["tabela_espelho_vendas"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Cadastro do empreendimento nos sistemas internos e portais.",
    },
    {
        "id": "contratacao_pj",
        "nome": "Contratação PJ",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["briefing_inicial"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Contratação de pessoas jurídicas para o lançamento.",
    },
    {
        "id": "represamento",
        "nome": "Represamento",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 30,
        "dependencias": ["cadastro"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Represamento de clientes interessados antes do lançamento oficial.",
    },
    {
        "id": "quadro_nb",
        "nome": "Quadro NB",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 20,
        "dependencias": ["ap_final_orcamento"],
        "condicional": None,
        "responsavel": "Produto/Projetos",
        "descricao": "Quadro de áreas conforme NBR.",
    },
    {
        "id": "demolicao",
        "nome": "Demolição",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 75,
        "dependencias": ["escritura"],
        "condicional": None,
        "responsavel": "Engenharia",
        "descricao": "Retirada de edificações existentes no terreno.",
    },
    {
        "id": "pdv",
        "nome": "PDV (Ponto de Venda)",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 60,
        "dependencias": ["execucao_stand"],
        "condicional": None,
        "responsavel": "Engenharia/PDV",
        "descricao": "Estrutura física montada para atendimento ao público no lançamento.",
    },
    {
        "id": "meeting_lancamento",
        "nome": "Meeting de Lançamento",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 1,
        "dependencias": ["pdv", "mkt_preparacao", "ri"],
        "condicional": None,
        "responsavel": "Marketing",
        "descricao": "Evento interno de alinhamento das equipes antes do lançamento.",
    },
    {
        "id": "lancamento",
        "nome": "Lançamento",
        "grupo": "Preparativos Lançamento",
        "subgrupo": "Comercialização",
        "fase": "Preparativos Lançamento",
        "duracao_dias": 1,
        "dependencias": ["meeting_lancamento", "contratacao_cef"],
        "condicional": None,
        "responsavel": "Negócios",
        "descricao": "Início oficial da comercialização das unidades do empreendimento.",
    },
]

FLAGS_CONDICIONAIS = {
    "graprohab": "GRAPROHAB (800+ unidades / MCMV)",
    "condephaat": "CONDEPHAAT (tombamento ou área de influência)",
    "decont": "DECONT (terreno contaminado)",
    "ceuso": "CEUSO (exceção ao zoneamento)",
    "depave": "DEPAVE (remoção de árvores)",
    "comar": "COMAR Completo (fora dos parâmetros padrão)",
    "retificacao": "Retificação de Matrícula",
    "desmembramento": "Desmembramento de terreno",
}

ALIASES_IMPORTACAO = {
    "levantamento planialtimétrico": "planialtimetrico",
    "planialtimétrico": "planialtimetrico",
    "estudo hidrológico": "laudo_hidrologico",
    "laudo hidrológico": "laudo_hidrologico",
    "pré sondagem": "sondagem",
    "pré-sondagem": "sondagem",
    "orçamento da demolição": "orcamento_demolicao",
    "orçamento demolição": "orcamento_demolicao",
    "cadastramento arbóreo": "cadastro_arboreo",
    "cadastro arbóreo": "cadastro_arboreo",
    "estudos de passivo": "investigacao_ambiental",
    "estudos ambientais": "investigacao_ambiental",
    "estimativa de custo passivo ambiental": "estimativa_custo_passivo",
    "passagem terrenos-negócios": "passagem_terrenos",
    "reunião de passagem do terreno": "reuniao_passagem_terreno",
    "vistoria do terreno": "vistoria_terreno",
    "acesso prodesp": "acesso_terreno",
    "acesso terreno": "acesso_terreno",
    "due diligence": "due_diligence",
    "pré-comar": "pre_comar",
    "ficha técnica": "ficha_tecnica",
    "aprovação projetos de reforço sabesp": "elaboracao_projetos_sabesp",
    "pl protocolo plano integrado": "pl_protocolo",
    "pl protocolo 3100": None,
    "diretrizes de água e esgoto": "diretrizes_agua_esgoto",
    "diretrizes de energia": "diretrizes_energia",
    "relatório final passivo ambiental": "relatorio_final_passivo",
    "termo de compromisso ambiental - tca": "tca",
    "custos ambientais ccl": "custos_ambientais_ccl",
    "reunião de passagem ep": "reuniao_passagem_ep",
    "validação ep": "validacao_ep",
    "revisão final do ep/base r00 ap": "revisao_final_ep",
    "ep arquitetura compatibilizado": "ep_arq_compatibilizado",
    "ap arquitetura compatibilizado": "ap_arq_compatibilizado",
    "ap final para orçamento": "ap_final_orcamento",
    "elaboração projetos de reforço sabesp": "elaboracao_projetos_sabesp",
    "aprovação completa": "aprovacao_completa",
    "alvará de execução": "alvara_execucao",
    "montagem do processo de regularização": "montagem_processo_regularizacao",
    "unificação da matrícula": "unificacao_matricula",
    "laudo de posse": "laudo_posse",
    "imissão da posse": "imissao_posse",
    "laudo de vizinhos": "laudo_vizinhos",
    "alvará de tapume": "alvara_tapume",
    "regularização do contribuinte": "regularizacao_contribuinte",
    "pl sabesp": "pl_sabesp",
    "pl final": "pl_final",
    "pl cartório": "pl_cartorio",
    "confirmação mix": "confirmacao_mix",
    "classificação do ruído": "classificacao_ruido",
    "ca de confirmação interna": "ca_confirmacao_interna",
    "ri - prenotação": "ri_prenotacao",
    "ri - obtenção": "ri_obtencao",
    "projeto stand": "projeto_stand",
    "execução de stand": "execucao_stand",
    "imagens": "imagens",
    "tour virtual": "tour_virtual",
    "maquete": "maquete",
    "memorial descritivo": "memorial_descritivo",
    "planta de contrato": "planta_contrato",
    "briefing inicial": "briefing_inicial",
    "materiais offline": "materiais_offline",
    "materiais online": "materiais_online",
    "orçamento final": "orcamento_final",
    "tabela e espelho de vendas": "tabela_espelho_vendas",
    "previsão de condomínio": "previsao_condominio",
    "contrato cliente": "contrato_cliente",
    "cadastro": "cadastro",
    "contratação pj": "contratacao_pj",
    "represamento": "represamento",
    "quadro nb": "quadro_nb",
}